// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqxYJ7Hjw7QTRCuq616ANjbh2QVDvixkU',
    appId: '1:515173360940:web:d57bdcc18fe70591477889',
    messagingSenderId: '515173360940',
    projectId: 'hacksync-16903',
    authDomain: 'hacksync-16903.firebaseapp.com',
    storageBucket: 'hacksync-16903.firebasestorage.app',
    measurementId: 'G-ZKZZF3D7MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWfjEysdZb2Sxa81fnMMPkck20ZGVNuU',
    appId: '1:515173360940:android:89fffade9ea8f354477889',
    messagingSenderId: '515173360940',
    projectId: 'hacksync-16903',
    storageBucket: 'hacksync-16903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDks5OAUa3j7pavD-p3HC4J0uG3SxS1Co4',
    appId: '1:515173360940:ios:95edc63fe648169e477889',
    messagingSenderId: '515173360940',
    projectId: 'hacksync-16903',
    storageBucket: 'hacksync-16903.firebasestorage.app',
    iosBundleId: 'com.example.hacksync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDks5OAUa3j7pavD-p3HC4J0uG3SxS1Co4',
    appId: '1:515173360940:ios:95edc63fe648169e477889',
    messagingSenderId: '515173360940',
    projectId: 'hacksync-16903',
    storageBucket: 'hacksync-16903.firebasestorage.app',
    iosBundleId: 'com.example.hacksync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqxYJ7Hjw7QTRCuq616ANjbh2QVDvixkU',
    appId: '1:515173360940:web:1b15b6df85acd927477889',
    messagingSenderId: '515173360940',
    projectId: 'hacksync-16903',
    authDomain: 'hacksync-16903.firebaseapp.com',
    storageBucket: 'hacksync-16903.firebasestorage.app',
    measurementId: 'G-P9GXEV4QKS',
  );
}
